dwindle {
    preserve_split = true
    smart_split = false
    smart_resizing = true
    precise_mouse_move = false
}

# Moving Windows
bind = Super+Shift, Left, movewindow, l
bind = Super+Shift, Right, movewindow, r
bind = Super+Shift, Up, movewindow, u
bind = Super+Shift, Down, movewindow, d

# Mouse
bindm = Super, mouse:272, movewindow
bindm = Super, mouse:274, movewindow
bindm = Super, mouse:273, resizewindow

# Window State Management
bind = Super, P, pin
bind = Super, D, fullscreen, 1
bind = Super, F, fullscreen, 0
bind = Super+Alt, F, fullscreenstate, 0 3

# Focus Management
## Directions way
bind = Super, Left, movefocus, l
bind = Super, Right, movefocus, r
bind = Super, Up, movefocus, u
bind = Super, Down, movefocus, d
## Brackets way
bind = Super, BracketLeft, movefocus, l
bind = Super, BracketRight, movefocus, r

