# MONITOR CONFIG
monitor= eDP-1 ,disable # preferred,auto,1

bindl=,switch:on:Lid Switch,exec,$scriptsDir/lid_off.sh
bindl=,switch:off:Lid Switch,exec,$scriptsDir/lid_off.sh

monitorv2 {
  output = $external_monitor_name
  mode = $external_monitor_mode
}
