# Critical
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = NVD_BACKEND,direct
env = ELECTRON_OZONE_PLATFORM_HINT,auto
env = GBM_BACKEND,nvidia-drm
env = __GL_GSYNC_ALLOWED, 1
env = __GL_VRR_ALLOWED, 1

# Hybrid GPU stuff
env = AQ_FORCE_LINEAR_BLIT,0
env = AQ_MGPU_NO_EXPLICIT,1
env = AQ_NO_MODIFIERS,1
# env = AQ_DRM_DEVICES,/dev/dri/card0:/dev/dri/card1
