plugin {
    hyprbars {
        bar_text_font = Tahoma
        bar_height = 30
        bar_padding = 10
        bar_button_padding = 10
        bar_precedence_over_border = true
        bar_part_of_window = true

        bar_color = rgb(0160F6)
        col.text = rgb(FFFFFF)

        hyprbars-button = rgb(E64F1D), 13, , hyprctl dispatch killactive
        hyprbars-button = rgb(4078F6), 13, , hyprctl dispatch fullscreen 1
        hyprbars-button = rgb(4078F6), 13, , hyprctl dispatch movetoworkspacesilent special
    }
}
