scrolling {
    fullscreen_on_one_column = false
    follow_focus = true
    focus_fit_method = 1
    explicit_column_widths = 0.33, 0.66, 1.0
    column_width = 0.5
    direction = right
}

# Focus Management
bind = Super, Right, layoutmsg, move +col
bind = Super, Left, layoutmsg, move -col

# Fine pixel scroll
bind = Super ALT, Right, layoutmsg, move +200
bind = Super ALT, Left, layoutmsg, move -200

# Moving Windows
bind = Super CTRL, Right, layoutmsg, movewindowto r
bind = Super CTRL, Left, layoutmsg, movewindowto l
bind = Super CTRL, Up, layoutmsg, movewindowto u
bind = Super CTRL, Down, layoutmsg, movewindowto d

# Promote window to its own column
bind = Super, P, layoutmsg, promote

# Swap columns
bind = Super CTRL, Right, layoutmsg, swapcol r
bind = Super CTRL, Left, layoutmsg, swapcol l

# Column Resizing
bind = Super SHIFT, Right, layoutmsg, colresize +conf
bind = Super SHIFT, Left, layoutmsg, colresize -conf
bind = Super SHIFT, Up, layoutmsg, colresize +0.1
bind = Super SHIFT, Down, layoutmsg, colresize -0.1
bind = Super CTRL ALT, equal, layoutmsg, colresize all 0.5

# Fit / Scroll to position
bind = Super, Home, layoutmsg, fit tobeg
bind = Super, End, layoutmsg, fit toend
bind = Super, A, layoutmsg, fit active
bind = Super SHIFT, A, layoutmsg, fit all
bind = Super CTRL, A, layoutmsg, fit visible

# Move entire column to workspace
bind = Super Alt, 1, layoutmsg, movecoltoworkspace 1
bind = Super Alt, 2, layoutmsg, movecoltoworkspace 2
bind = Super Alt, 3, layoutmsg, movecoltoworkspace 3
bind = Super Alt, 4, layoutmsg, movecoltoworkspace 4
bind = Super Alt, 5, layoutmsg, movecoltoworkspace 5
bind = Super Alt, 6, layoutmsg, movecoltoworkspace 1
bind = Super Alt, 7, layoutmsg, movecoltoworkspace 2
bind = Super Alt, 8, layoutmsg, movecoltoworkspace 3
bind = Super Alt, 9, layoutmsg, movecoltoworkspace 4
bind = Super Alt, 0, layoutmsg, movecoltoworkspace 5

bind = Super Shift CTRL, right, layoutmsg, movecoltoworkspace +1
bind = Super Shift CTRL, left, layoutmsg, movecoltoworkspace -1
bind = Super Alt, S, layoutmsg, movecoltoworkspace special

# Window State Management
bind = Super, D, layoutmsg, colresize 1
bind = Super, F, fullscreen
bind = Super Alt, F, fullscreenstate, 1

# Mouse
bindm = Super, mouse:272, movewindow
bindm = Super, mouse:274, movewindow
bindm = Super, mouse:273, resizewindow

# Gestures
gesture = 3, Right, dispatcher, layoutmsg, move -col
gesture = 3, Left,  dispatcher, layoutmsg, move +col
gesture = 3, Right, mod:Super SHIFT, dispatcher, layoutmsg, colresize +conf
gesture = 3, Left,  mod:Super SHIFT, dispatcher, layoutmsg, colresize -conf