$terminal = foot
$terminal_alt = foot
$browser = firefox
$browser_alt = firefox
$editor = zeditor
$file_manager = dolphin

$blur = true
$unblur_apps = false
$blur_size = 2
$blur_passes = 4
$xray = true
$ignore_opacity = true
$new_optimizations = true
$shadows = true
$shadows_power = 2
$shadows_range = 20
$gaps_in = 8
$gaps_out = 15
$gaps_special = 40
$borders = 0
$rounding = 27
$rounding_power = 2
$layers_alpha = 0.4
$applications_opacity = 0.8111623863028357
$hypr_col_alpha = 60
$font_main = "Noto Sans"
$layout = dwindle
$debug_overlay = false
$vrr = true
$vfr = true
$cursor_theme = GoogleDot-White
$cursor_size = 24
$animation_mode = slidevert
$scrolling_orientation = vertical
$external_monitor_mode = 1920x1080@72
$external_monitor_name = DP-4
$extra_external_monitor_name = DP-5
$extra_external_monitor_mode = 1680x1050@65
